# -*- coding: utf-8 -*-
"""doctamper_mix_transformer_unet_real_receipt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n4j7Gz2dIQETzSJA3kyPmKVMvgrofrOl

# DocTamper — Inference Pipeline trên ảnh hóa đơn thực tế (MiT + U-Net)

**Mô hình:** MiT-B2 encoder + U-Net decoder (qua `segmentation_models_pytorch`)
- Huấn luyện trên DocTamper dataset (phân đoạn nhị phân: nền vs vùng chỉnh sửa)
- Checkpoint chứa `model_state`, `encoder`, `img_size`, `best_val_iou`

**Pipeline này thực hiện:**
1. Nạp checkpoint đã huấn luyện
2. Chạy inference trên 2 folder: `normal` (ảnh gốc) và `pts` (ảnh đã chỉnh sửa qua Photoshop)
3. **Giữ nguyên kích thước ảnh gốc** — không ép về 512×512 (người dùng tự resize trước nếu cần)
4. Xuất kết quả:
   - Hiển thị từng ảnh + mask trên Colab
   - File CSV kết quả cho từng hình ảnh
   - Confusion matrix
   - Folder chứa hình ảnh overlay mask cho ảnh được phát hiện là giả mạo

## (1) Cài đặt / Setup

Chạy trên **GPU** runtime. Runtime → Change runtime type → GPU.
"""

!pip install -q segmentation-models-pytorch timm pandas matplotlib scikit-learn tqdm

"""## (2) Mount Google Drive"""

from pathlib import Path

try:
    from google.colab import drive
    drive.mount("/content/drive")
except ImportError:
    print("Không phải Colab — bỏ qua mount Drive.")

"""## (3) Cấu hình đường dẫn & tham số

- `CHECKPOINT_PATH`: đường dẫn tới file checkpoint `.pt`
- `DATA_ROOT`: thư mục chứa 2 folder con `normal` và `pts`
- `NORMAL_FOLDER_NAME` / `PTS_FOLDER_NAME`: tên folder ảnh gốc / ảnh giả mạo
- `TAMPER_PIXEL_THRESHOLD`: ngưỡng tỷ lệ pixel giả mạo để phân loại ảnh là "tampered"
- `OUTPUT_DIR`: thư mục lưu kết quả (CSV, mask overlay, confusion matrix)
"""

CHECKPOINT_PATH = Path("/content/drive/MyDrive/doctamper/mit_unet_doctamper_best.pt")

STRING_ROOT = "/content/drive/MyDrive/doctamper/Viet-Receipt-VQA-TestSet"

# STRING_ROOT = "/content/drive/MyDrive/doctamper/Other-Test"

DATA_ROOT = Path(STRING_ROOT)
NORMAL_FOLDER_NAME = "normal"   # folder chứa ảnh không gian lận
PTS_FOLDER_NAME    = "pts"      # folder chứa ảnh đã chỉnh sửa qua Photoshop

# Ngưỡng: nếu tỷ lệ pixel dự đoán "tampered" >= threshold → phân loại là tampered
TAMPER_PIXEL_THRESHOLD = 0.0001   # 0.1% pixel

OUTPUT_DIR = Path(STRING_ROOT +"/inference_results")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Tên encoder (phải khớp với checkpoint)
ENCODER_NAME = "mit_b2"

print(f"Checkpoint : {CHECKPOINT_PATH}")
print(f"Data root  : {DATA_ROOT}")
print(f"  normal   : {DATA_ROOT / NORMAL_FOLDER_NAME}")
print(f"  pts      : {DATA_ROOT / PTS_FOLDER_NAME}")
print(f"Output dir : {OUTPUT_DIR}")
print(f"Threshold  : {TAMPER_PIXEL_THRESHOLD}")

"""## (4) Nạp mô hình & checkpoint

Khởi tạo mô hình **MiT-B2 + U-Net** (2 lớp: nền / vùng chỉnh sửa), sau đó nạp trọng số từ checkpoint.
"""

import warnings
warnings.filterwarnings("ignore", category=UserWarning)

import numpy as np
import torch
import torch.nn as nn
import segmentation_models_pytorch as smp
from PIL import Image
from torchvision import transforms
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
import pandas as pd
import os

torch.backends.cudnn.benchmark = True
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", DEVICE)

USE_BF16 = False
if DEVICE.type == "cuda":
    print("GPU:", torch.cuda.get_device_name(0))
    USE_BF16 = torch.cuda.is_bf16_supported()
    print("BF16 autocast:", USE_BF16)

use_amp = DEVICE.type == "cuda"
amp_dtype = torch.float16

# --- Khởi tạo mô hình ---
model = smp.Unet(
    encoder_name=ENCODER_NAME,
    encoder_weights=None,
    in_channels=3,
    classes=2,
    activation=None,
)
model = model.to(DEVICE)

# --- Nạp checkpoint ---
assert CHECKPOINT_PATH.is_file(), f"Không tìm thấy checkpoint: {CHECKPOINT_PATH}"
try:
    ck = torch.load(CHECKPOINT_PATH, map_location=DEVICE, weights_only=False)
except TypeError:
    ck = torch.load(CHECKPOINT_PATH, map_location=DEVICE)

model.load_state_dict(ck["model_state"])
model.eval()

print(f"Đã nạp checkpoint: {CHECKPOINT_PATH}")
print(f"  Encoder  : {ck.get('encoder', 'N/A')}")
print(f"  IMG_SIZE : {ck.get('img_size', 'N/A')}")
print(f"  Val IoU  : {ck.get('best_val_iou', 'N/A')}")

"""## (5) Hàm inference — giữ nguyên kích thước ảnh gốc

Ảnh được giữ nguyên kích thước gốc khi đưa vào mô hình.
Chỉ áp dụng `ToTensor()` + `Normalize(ImageNet)`. Mask đầu ra có cùng kích thước với ảnh đầu vào.
"""

IMG_NORMALIZE = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

IMAGENET_MEAN = torch.tensor([0.485, 0.456, 0.406], device=DEVICE).view(1, 3, 1, 1)
IMAGENET_STD  = torch.tensor([0.229, 0.224, 0.225], device=DEVICE).view(1, 3, 1, 1)

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tiff"}


def collect_image_paths(folder: Path) -> list:
    """Thu thập tất cả file ảnh trong folder, sắp xếp theo tên."""
    if not folder.is_dir():
        print(f"WARNING: Folder không tồn tại: {folder}")
        return []
    paths = []
    for f in sorted(folder.iterdir()):
        if f.suffix.lower() in IMAGE_EXTENSIONS and f.is_file():
            paths.append(f)
    return paths


@torch.no_grad()
def infer_single_image(image_path: Path) -> dict:
    """
    Chạy inference trên 1 ảnh, giữ nguyên kích thước gốc.
    Returns dict với: image_pil, mask_np (H,W binary 0/1),
                      prob_map (H,W float), tamper_ratio, predicted_label
    """
    image_pil = Image.open(image_path).convert("RGB")
    w_orig, h_orig = image_pil.size

    x = IMG_NORMALIZE(image_pil).unsqueeze(0).to(DEVICE, non_blocking=True)

    with torch.amp.autocast("cuda", dtype=amp_dtype, enabled=use_amp):
        logits = model(x)  # [1, 2, H, W]

    prob_fg = torch.softmax(logits, dim=1)[0, 1].cpu().numpy()   # P(tampered)
    mask_binary = (logits.argmax(dim=1)[0]).cpu().numpy().astype(np.uint8)  # 0 or 1

    tamper_pixels = mask_binary.sum()
    total_pixels = mask_binary.shape[0] * mask_binary.shape[1]
    tamper_ratio = tamper_pixels / total_pixels

    predicted_tampered = tamper_ratio >= TAMPER_PIXEL_THRESHOLD

    return {
        "image_path": image_path,
        "image_pil": image_pil,
        "w_orig": w_orig,
        "h_orig": h_orig,
        "mask_np": mask_binary,
        "prob_map": prob_fg,
        "tamper_ratio": tamper_ratio,
        "tamper_pixels": int(tamper_pixels),
        "total_pixels": int(total_pixels),
        "predicted_tampered": predicted_tampered,
    }


def run_inference_on_folder(folder: Path, ground_truth_label: int, label_name: str) -> list:
    """
    Chạy inference trên tất cả ảnh trong folder.
    ground_truth_label: 0 = normal, 1 = tampered
    Returns list of result dicts.
    """
    paths = collect_image_paths(folder)
    print(f"\n{'='*60}")
    print(f"Folder: {folder.name} ({label_name}) — {len(paths)} ảnh")
    print(f"Ground truth label: {ground_truth_label} ({'tampered' if ground_truth_label == 1 else 'normal'})")
    print(f"{'='*60}")

    results = []
    for p in tqdm(paths, desc=f"Inference [{label_name}]"):
        res = infer_single_image(p)
        res["ground_truth"] = ground_truth_label
        res["ground_truth_label"] = label_name
        results.append(res)

    correct = sum(1 for r in results if r["predicted_tampered"] == bool(ground_truth_label))
    print(f"Accuracy trên folder {label_name}: {correct}/{len(results)} ({100*correct/max(len(results),1):.1f}%)")
    return results


print("Các hàm inference đã sẵn sàng.")

"""## (6) Chạy inference & hiển thị kết quả từng ảnh

Chạy trên cả 2 folder. Hiển thị ảnh gốc + mask dự đoán cho từng hình.
- **Đỏ** = vùng mô hình phát hiện có chỉnh sửa
- Tiêu đề ghi nhận: tên file, ground truth, dự đoán, tỷ lệ pixel giả mạo
"""

normal_folder = DATA_ROOT / NORMAL_FOLDER_NAME
pts_folder    = DATA_ROOT / PTS_FOLDER_NAME

assert normal_folder.is_dir(), f"Folder normal không tồn tại: {normal_folder}"
assert pts_folder.is_dir(),    f"Folder pts không tồn tại: {pts_folder}"

results_normal = run_inference_on_folder(normal_folder, ground_truth_label=0, label_name="normal")
results_pts    = run_inference_on_folder(pts_folder,    ground_truth_label=1, label_name="pts")

all_results = results_normal + results_pts
print(f"\nTổng cộng: {len(all_results)} ảnh ({len(results_normal)} normal + {len(results_pts)} pts)")

def display_results(results: list, max_per_row: int = 4):
    """Hiển thị ảnh gốc + mask dự đoán, chia thành các hàng."""
    n = len(results)
    if n == 0:
        print("Không có kết quả để hiển thị.")
        return

    n_rows = (n + max_per_row - 1) // max_per_row

    for row_idx in range(n_rows):
        start = row_idx * max_per_row
        end = min(start + max_per_row, n)
        batch = results[start:end]
        cols = len(batch)

        fig, axes = plt.subplots(2, cols, figsize=(5 * cols, 8))
        if cols == 1:
            axes = np.array(axes).reshape(2, 1)

        for i, res in enumerate(batch):
            gt = "NORMAL" if res["ground_truth"] == 0 else "TAMPERED"
            pred = "TAMPERED" if res["predicted_tampered"] else "NORMAL"
            correct = "✓" if (res["predicted_tampered"] == bool(res["ground_truth"])) else "✗"
            ratio_pct = res["tamper_ratio"] * 100

            axes[0, i].imshow(res["image_pil"])
            axes[0, i].set_title(
                f"{res['image_path'].name}\nGT: {gt} | Pred: {pred} {correct}\n"
                f"Tamper: {ratio_pct:.2f}%",
                fontsize=8,
            )
            axes[0, i].axis("off")

            axes[1, i].imshow(res["mask_np"], vmin=0, vmax=1, cmap="Reds")
            axes[1, i].set_title("Mask dự đoán (vùng chỉnh sửa)", fontsize=8)
            axes[1, i].axis("off")

        plt.tight_layout()
        plt.show()


print("=== KẾT QUẢ FOLDER: NORMAL ===")
display_results(results_normal, max_per_row=4)

print("\n=== KẾT QUẢ FOLDER: PTS (TAMPERED) ===")
display_results(results_pts, max_per_row=4)

"""## (7) Xuất kết quả CSV

File CSV chứa thông tin cho từng ảnh:
- Tên file, folder nguồn, kích thước gốc
- Ground truth, dự đoán, đúng/sai
- Tỷ lệ pixel giả mạo, số pixel giả mạo / tổng pixel
"""

rows = []
for r in all_results:
    rows.append({
        "filename":           r["image_path"].name,
        "folder":             r["ground_truth_label"],
        "width":              r["w_orig"],
        "height":             r["h_orig"],
        "ground_truth":       "tampered" if r["ground_truth"] == 1 else "normal",
        "prediction":         "tampered" if r["predicted_tampered"] else "normal",
        "correct":            r["predicted_tampered"] == bool(r["ground_truth"]),
        "tamper_ratio":       round(r["tamper_ratio"], 6),
        "tamper_ratio_pct":   round(r["tamper_ratio"] * 100, 4),
        "tamper_pixels":      r["tamper_pixels"],
        "total_pixels":       r["total_pixels"],
    })

df = pd.DataFrame(rows)

csv_path = OUTPUT_DIR / "inference_results.csv"
df.to_csv(csv_path, index=False)

n_correct = df["correct"].sum()
n_total = len(df)
print(f"Overall Accuracy: {n_correct}/{n_total} ({100*n_correct/n_total:.1f}%)")
print(f"\nCSV đã lưu tại: {csv_path}")
print(f"\n--- Bảng tổng hợp ---")
display(df)

"""## (8) Confusion Matrix & Classification Report

Ma trận nhầm lẫn ở cấp **ảnh** (image-level):
- **Positive (1)** = ảnh giả mạo (tampered / pts)
- **Negative (0)** = ảnh gốc (normal)
"""

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
)

y_true = [r["ground_truth"] for r in all_results]
y_pred = [int(r["predicted_tampered"]) for r in all_results]

cm = confusion_matrix(y_true, y_pred, labels=[0, 1])

fig, ax = plt.subplots(figsize=(6, 5))
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Normal (0)", "Tampered (1)"],
)
disp.plot(ax=ax, cmap="Blues", values_format="d")
ax.set_title("Confusion Matrix (Image-Level)", fontsize=14)
plt.tight_layout()

cm_path = OUTPUT_DIR / "confusion_matrix.png"
fig.savefig(cm_path, dpi=150, bbox_inches="tight")
print(f"Confusion matrix đã lưu tại: {cm_path}")
plt.show()

print("\n--- Classification Report ---")
print(classification_report(y_true, y_pred, target_names=["Normal", "Tampered"], digits=4))

acc  = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred, zero_division=0)
rec  = recall_score(y_true, y_pred, zero_division=0)
f1   = f1_score(y_true, y_pred, zero_division=0)

metrics_summary = pd.DataFrame([{
    "Accuracy":  round(acc, 4),
    "Precision": round(prec, 4),
    "Recall":    round(rec, 4),
    "F1-Score":  round(f1, 4),
}])
print("--- Tổng hợp Metrics ---")
display(metrics_summary)

"""## (9) Lưu ảnh overlay mask cho ảnh phát hiện giả mạo

Với mỗi ảnh được mô hình dự đoán là **tampered**, tạo ảnh overlay:
- Ảnh gốc phủ mask màu đỏ bán trong suốt tại vùng gian lận
- Lưu vào folder `OUTPUT_DIR/tampered_masks/`
"""

MASK_OUTPUT_DIR = OUTPUT_DIR / "tampered_masks"
MASK_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OVERLAY_ALPHA = 0.45
OVERLAY_COLOR = np.array([255, 0, 0], dtype=np.uint8)  # Đỏ


def create_overlay(image_pil: Image.Image, mask_np: np.ndarray, alpha: float = OVERLAY_ALPHA) -> Image.Image:
    """
    Tạo ảnh overlay: ảnh gốc + mask đỏ bán trong suốt tại vùng giả mạo.
    mask_np: (H, W) binary 0/1
    """
    img_arr = np.array(image_pil).copy()
    h_img, w_img = img_arr.shape[:2]
    h_mask, w_mask = mask_np.shape

    if (h_img, w_img) != (h_mask, w_mask):
        mask_pil = Image.fromarray((mask_np * 255).astype(np.uint8))
        mask_pil = mask_pil.resize((w_img, h_img), Image.NEAREST)
        mask_resized = np.array(mask_pil) > 127
    else:
        mask_resized = mask_np.astype(bool)

    overlay = img_arr.copy()
    overlay[mask_resized] = (
        (1 - alpha) * img_arr[mask_resized].astype(np.float32)
        + alpha * OVERLAY_COLOR.astype(np.float32)
    ).astype(np.uint8)

    return Image.fromarray(overlay)


detected_tampered = [r for r in all_results if r["predicted_tampered"]]
print(f"Số ảnh dự đoán là tampered: {len(detected_tampered)}/{len(all_results)}")

saved_count = 0
for r in tqdm(detected_tampered, desc="Lưu overlay"):
    overlay_img = create_overlay(r["image_pil"], r["mask_np"])
    src_folder = r["ground_truth_label"]
    save_name = f"{src_folder}__{r['image_path'].stem}_overlay.jpg"
    save_path = MASK_OUTPUT_DIR / save_name
    overlay_img.save(save_path, quality=95)
    saved_count += 1

print(f"\nĐã lưu {saved_count} ảnh overlay vào: {MASK_OUTPUT_DIR}")

if detected_tampered:
    print("\n--- Xem trước một số ảnh overlay ---")
    preview = detected_tampered[:8]
    n = len(preview)
    cols = min(n, 4)
    rows = (n + cols - 1) // cols
    fig, axes = plt.subplots(rows, cols, figsize=(5 * cols, 5 * rows))
    axes = np.array(axes).reshape(-1) if n > 1 else [axes]

    for i, r in enumerate(preview):
        overlay_img = create_overlay(r["image_pil"], r["mask_np"])
        gt = "GT:NORMAL" if r["ground_truth"] == 0 else "GT:TAMPERED"
        axes[i].imshow(overlay_img)
        axes[i].set_title(
            f"{r['image_path'].name}\n{gt} → Pred:TAMPERED\nTamper: {r['tamper_ratio']*100:.2f}%",
            fontsize=8,
        )
        axes[i].axis("off")

    for j in range(i + 1, len(axes)):
        axes[j].axis("off")

    plt.tight_layout()
    plt.show()

"""## (10) Tổng kết

Tất cả output đã được lưu vào `OUTPUT_DIR`:
- `inference_results.csv` — kết quả chi tiết cho từng ảnh
- `confusion_matrix.png` — hình ảnh confusion matrix
- `tampered_masks/` — folder chứa ảnh overlay mask cho các ảnh phát hiện giả mạo

**Lưu ý:**
- Ngưỡng `TAMPER_PIXEL_THRESHOLD` có thể điều chỉnh tùy theo yêu cầu
- Ảnh được giữ nguyên kích thước gốc khi inference. Nếu kích thước ảnh quá lớn/nhỏ so với 512×512 (kích thước training), hãy tự resize trước khi đưa vào pipeline
"""

print("="*60)
print("TỔNG KẾT PIPELINE INFERENCE")
print("="*60)
print(f"Checkpoint       : {CHECKPOINT_PATH.name}")
print(f"Encoder          : {ck.get('encoder', ENCODER_NAME)}")
print(f"Threshold        : {TAMPER_PIXEL_THRESHOLD} ({TAMPER_PIXEL_THRESHOLD*100}%)")
print(f"Tổng ảnh         : {len(all_results)}")
print(f"  - Normal       : {len(results_normal)}")
print(f"  - PTS          : {len(results_pts)}")
print(f"Accuracy         : {acc:.4f} ({int(acc*len(all_results))}/{len(all_results)})")
print(f"Precision        : {prec:.4f}")
print(f"Recall           : {rec:.4f}")
print(f"F1-Score         : {f1:.4f}")
print(f"Ảnh overlay lưu  : {saved_count} ảnh")
print(f"Output dir       : {OUTPUT_DIR}")
print("="*60)

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path
from sklearn.metrics import ConfusionMatrixDisplay

def evaluate_from_counts(tn, fp, fn, tp, output_dir="outputs"):
    """
    Evaluates model performance using raw TP, FP, FN, TN counts.
    """
    OUT_DIR = Path(output_dir)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # 1. Manually construct the Confusion Matrix array
    # Format: [[TN, FP], [FN, TP]]
    cm = np.array([[tn, fp], [fn, tp]])

    # 2. Calculate Metrics from formulas
    # We use LaTeX-style logic for clarity:
    # Accuracy = (TP + TN) / Total
    total = tn + fp + fn + tp
    acc  = (tp + tn) / total if total > 0 else 0
    prec = tp / (tp + fp) if (tp + fp) > 0 else 0
    rec  = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1   = 2 * (prec * rec) / (prec + rec) if (prec + rec) > 0 else 0

    # 3. Visualization
    fig, ax = plt.subplots(figsize=(6, 5))
    disp = ConfusionMatrixDisplay(
        confusion_matrix=cm,
        display_labels=["Normal (0)", "Tampered (1)"],
    )
    disp.plot(ax=ax, cmap="Blues", values_format="d")
    ax.set_title("Confusion Matrix (Manual Input)", fontsize=14)

    cm_path = OUT_DIR / "manual_confusion_matrix.png"
    plt.tight_layout()
    fig.savefig(cm_path, dpi=150)
    plt.show()

    # 4. Summary Table
    metrics_summary = pd.DataFrame([{
        "True Negatives": tn,
        "False Positives": fp,
        "False Negatives": fn,
        "True Positives": tp,
        "Accuracy": round(acc, 4),
        "Precision": round(prec, 4),
        "Recall": round(rec, 4),
        "F1-Score": round(f1, 4),
    }])

    return metrics_summary

# ==========================================
# CUSTOM VALUE INPUT
# ==========================================
# Enter your counts here:
my_tn = 452  # Predicted Normal, actually Normal
my_fp = 48   # Predicted Tampered, actually Normal
my_fn = 37   # Predicted Normal, actually Tampered
my_tp = 463  # Predicted Tampered, actually Tampered

summary_df = evaluate_from_counts(tn=my_tn, fp=my_fp, fn=my_fn, tp=my_tp)
display(summary_df)