# -*- coding: utf-8 -*-
"""Intern VL3.6-8B Metric.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WI7x_uFMxrgelqINR_RLOv_GsyPgXu2L
"""

import matplotlib.pyplot as plt
import numpy as np

# Data from Table 2
batch_sizes = [1, 4, 8, 16, 24, 48, 64]
tokens_per_sec = [67.95, 154.25, 225.26, 263.25, 367.75, 472.84, 453.80]
improvement = [1.0, 2.27, 3.32, 3.87, 5.41, 6.94, 6.66]

# Formatting for academic style
plt.rcParams.update({'font.size': 12, 'font.family': 'serif'})
fig, ax1 = plt.subplots(figsize=(10, 6))

# Plot Throughput (Tokens/sec)
color_blue = '#1f77b4'
line1 = ax1.plot(batch_sizes, tokens_per_sec, marker='o', color=color_blue,
                 linewidth=2, label='Throughput (Tokens/sec)')
ax1.set_xlabel('Batch Size', fontweight='bold')
ax1.set_ylabel('Throughput (Tokens/sec)', color=color_blue, fontweight='bold')
ax1.tick_params(axis='y', labelcolor=color_blue)
ax1.grid(True, linestyle='--', alpha=0.6)

# Plot Improvement Factor on the secondary Y-axis
ax2 = ax1.twinx()
color_red = '#d62728'
line2 = ax2.plot(batch_sizes, improvement, marker='s', linestyle='--',
                 color=color_red, alpha=0.8, label='Improvement Factor')
ax2.set_ylabel('Improvement (x)', color=color_red, fontweight='bold')
ax2.tick_params(axis='y', labelcolor=color_red)

# Annotation for Optimal Batch Size
ax1.annotate(f'Optimal BS=48\n({max(tokens_per_sec)} tok/s)',
             xy=(48, 472.84), xytext=(30, 420),
             arrowprops=dict(facecolor='black', shrink=0.05, width=1, headwidth=8),
             fontsize=10, fontweight='bold', bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="black", lw=1))

plt.title('Performance Scaling of InternVL3.5-8B-Flash on NVIDIA A100 80GB', pad=20)
fig.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Data from Table 2
batch_sizes = [1, 4, 8, 16, 24, 48, 64]
wall_time = [4009, 1820, 1212, 1035, 741, 577, 601]
requests_per_sec = [0.29, 0.64, 0.96, 1.13, 1.58, 2.02, 1.94]
tokens_per_sec = [67.95, 154.25, 225.26, 263.25, 367.75, 472.84, 453.80]
improvement = ["1.00x", "2.27x", "3.32x", "3.87x", "5.41x", "6.94x", "6.66x"]

# Set academic style
plt.rcParams.update({'font.size': 11, 'font.family': 'serif'})
fig, ax1 = plt.subplots(figsize=(12, 7))

# Plot Tokens/sec on the left Y-axis
color_tokens = '#1f77b4'  # Deep blue
ax1.set_xlabel('Batch Size', fontweight='bold')
ax1.set_ylabel('Throughput (Tokens/sec)', color=color_tokens, fontweight='bold')
line1 = ax1.plot(batch_sizes, tokens_per_sec, marker='o', color=color_tokens,
                 linewidth=2.5, label='Tokens/sec', markersize=8)
ax1.tick_params(axis='y', labelcolor=color_tokens)
ax1.grid(True, linestyle='--', alpha=0.5)

# Plot Request/sec on the right Y-axis
ax2 = ax1.twinx()
color_reqs = '#2ca02c'  # Green
ax2.set_ylabel('Throughput (Request/sec)', color=color_reqs, fontweight='bold')
line2 = ax2.plot(batch_sizes, requests_per_sec, marker='s', color=color_reqs,
                 linewidth=2, linestyle='--', label='Request/sec', markersize=7)
ax2.tick_params(axis='y', labelcolor=color_reqs)

# Add Improvement labels at each data point
for i, txt in enumerate(improvement):
    ax1.annotate(txt,
                 (batch_sizes[i], tokens_per_sec[i]),
                 textcoords="offset points",
                 xytext=(0, 12),
                 ha='center',
                 fontsize=9,
                 fontweight='bold',
                 color='black')

# Title and Legend
plt.title('Inference Performance: InternVL3.5-8B-Flash on NVIDIA A100 80GB', pad=20, fontsize=14)
lines = line1 + line2
labels = [l.get_label() for l in lines]
ax1.legend(lines, labels, loc='upper left')

# Highlight the optimal point (Batch Size 48)
ax1.axvspan(44, 52, color='gray', alpha=0.1) # Highlight region

fig.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Data from Table 2
batch_sizes = [1, 4, 8, 16, 24, 48, 64]
requests_per_sec = [0.29, 0.64, 0.96, 1.13, 1.58, 2.02, 1.94]
tokens_per_sec = [67.95, 154.25, 225.26, 263.25, 367.75, 472.84, 453.80]
improvement = ["1.00x", "2.27x", "3.32x", "3.87x", "5.41x", "6.94x", "6.66x"]

# Academic style configuration
plt.rcParams.update({'font.size': 11, 'font.family': 'serif'})
fig, ax1 = plt.subplots(figsize=(12, 7))

# --- AXIS 1: TOKENS/SEC (Left) ---
color_tokens = '#1f77b4'
ax1.set_xlabel('Batch Size', fontweight='bold', labelpad=10)
ax1.set_ylabel('Throughput (Tokens/sec)', color=color_tokens, fontweight='bold')
line1 = ax1.plot(batch_sizes, tokens_per_sec, marker='o', color=color_tokens,
                 linewidth=2.5, label='Tokens/sec', markersize=8, zorder=3)
ax1.tick_params(axis='y', labelcolor=color_tokens)
ax1.grid(True, linestyle='--', alpha=0.4)

# THÊM PADDING TOP CHO TRỤC Y1 (Tăng giới hạn trên thêm 20%)
ax1.set_ylim(0, max(tokens_per_sec) * 1.2)

# --- AXIS 2: REQUEST/SEC (Right) ---
ax2 = ax1.twinx()
color_reqs = '#2ca02c'
ax2.set_ylabel('Throughput (Request/sec)', color=color_reqs, fontweight='bold')
line2 = ax2.plot(batch_sizes, requests_per_sec, marker='s', color=color_reqs,
                 linewidth=2, linestyle='--', label='Request/sec', markersize=7, zorder=2)
ax2.tick_params(axis='y', labelcolor=color_reqs)

# THÊM PADDING TOP CHO TRỤC Y2 (Tăng giới hạn trên tương ứng)
ax2.set_ylim(0, max(requests_per_sec) * 1.2)

# --- ANNOTATIONS (Improvement labels) ---
for i, txt in enumerate(improvement):
    # Sử dụng xytext=(0, 10) để nhãn cách điểm dữ liệu 10 points theo chiều dọc
    ax1.annotate(txt,
                 (batch_sizes[i], tokens_per_sec[i]),
                 textcoords="offset points",
                 xytext=(0, 12),
                 ha='center',
                 fontsize=10,
                 fontweight='bold',
                 bbox=dict(boxstyle="round,pad=0.2", fc="none", alpha=0.1, ec="none"))

# Title and Layout
plt.title('Performance Scalability: InternVL3.5-8B-Flash on NVIDIA A100 80GB', pad=25, fontsize=14)
lines = line1 + line2
labels = [l.get_label() for l in lines]
ax1.legend(lines, labels, loc='upper left', frameon=True, shadow=True)

fig.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Data from your image
tp, fp, fn = 2084, 225, 396

# Define the matrix for visualization
# Structure: [[TP, FP], [FN, 0]] - Note: TN is usually not applicable in extraction
matrix_data = np.array([[tp, fp],
                        [fn, 0]])

labels_text = np.array([["TP\n(Correct)", "FP\n(Excess/Wrong)"],
                        ["FN\n(Missing)", "N/A"]])

# Set up the visual style
plt.figure(figsize=(8, 6))
sns.set_theme(style="white")

# Create Heatmap without default annotations
ax = sns.heatmap(matrix_data, fmt="", cmap="Blues", cbar=True,
                 xticklabels=["Predicted Positive", "Predicted Negative"],
                 yticklabels=["Actual Positive", "Actual Negative"]) # Removed annot and annot_kws here

# Add custom text annotations (labels and values) with conditional coloring
for i in range(2):
    for j in range(2):
        if not (i == 1 and j == 1): # Skip the N/A cell
            val = matrix_data[i, j]
            label = labels_text[i, j]
            text_color = "white" if (i == 0 and j == 0) else "black" # White for TP, black for others

            # Place the label text (e.g., "TP\n(Correct)")
            ax.text(j + 0.5, i + 0.35, label, ha="center", va="center",
                    color=text_color, fontsize=12, fontweight="bold")

            # Place the value text (e.g., "Value: 2084")
            ax.text(j + 0.5, i + 0.7, f"Value: {val}", ha="center", va="center",
                    color=text_color, fontsize=10)

plt.title("Line-product Item Extraction Results Confusion Matrix", fontsize=12, pad=20)
plt.xlabel("Prediction Status", fontsize=12)
plt.ylabel("Ground Truth Status", fontsize=12)

plt.show()