#!/usr/bin/env bash
# Regenerate deploy/docker/.env.prod from Terraform outputs + preserved secrets/RunPod.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
TF_DIR="$ROOT/deploy/terraform/gcp"
OUT="$ROOT/deploy/docker/.env.prod"

cd "$TF_DIR"
if ! terraform output -json >/dev/null 2>&1; then
  echo "Run 'terraform apply' in $TF_DIR first." >&2
  exit 1
fi

ARTIFACTS_BUCKET="$(terraform output -raw artifacts_bucket)"
REDIS_HOST="$(terraform output -raw redis_host)"
CLOUD_SQL="$(terraform output -raw cloud_sql_connection)"
APP_VM_IP="$(terraform output -raw app_vm_ip)"
MONITORING_VM_IP="$(terraform output -raw monitoring_vm_ip)"
APP_SA="$(terraform output -raw app_service_account)"

GCP_PROJECT_ID="$(grep -E '^project_id\s*=' terraform.tfvars | sed -E 's/.*=\s*"(.*)".*/\1/')"
GCP_REGION="$(grep -E '^region\s*=' terraform.tfvars | sed -E 's/.*=\s*"(.*)".*/\1/')"
ENV_PREFIX="$(grep -E '^env\s*=' terraform.tfvars | sed -E 's/.*=\s*"(.*)".*/\1/')"
NAME_PREFIX="idp-${ENV_PREFIX}"

PREPROCESS_SA="${NAME_PREFIX}-preprocess@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
ORCH_SA="${NAME_PREFIX}-orch@${GCP_PROJECT_ID}.iam.gserviceaccount.com"

CALLBACK_SECRET=""
DB_PASSWORD=""
RUNPOD_POD_ID="${RUNPOD_POD_ID:-}"
EXTRACTION_URL="${EXTRACTION_URL:-}"
MOCK_EXTRACTION="${MOCK_EXTRACTION:-false}"

if [[ -f "$OUT" ]]; then
  CALLBACK_SECRET="$(grep '^CALLBACK_HMAC_SECRET=' "$OUT" | cut -d= -f2- || true)"
  DB_PASSWORD="$(grep '^DB_PASSWORD=' "$OUT" | cut -d= -f2- || true)"
  RUNPOD_POD_ID="${RUNPOD_POD_ID:-$(grep '^RUNPOD_POD_ID=' "$OUT" | cut -d= -f2- || true)}"
  EXTRACTION_URL="${EXTRACTION_URL:-$(grep '^EXTRACTION_URL=' "$OUT" | cut -d= -f2- || true)}"
  MOCK_EXTRACTION="$(grep '^MOCK_EXTRACTION=' "$OUT" | cut -d= -f2- || echo "$MOCK_EXTRACTION")"
fi

if [[ -z "$CALLBACK_SECRET" ]]; then
  CALLBACK_SECRET="$(openssl rand -hex 32)"
fi
if [[ -z "$DB_PASSWORD" ]]; then
  echo "Set DB_PASSWORD in $OUT after first run (Terraform module database password)." >&2
  DB_PASSWORD="CHANGE_ME"
fi

if [[ -n "$RUNPOD_POD_ID" && -z "$EXTRACTION_URL" ]]; then
  EXTRACTION_URL="https://${RUNPOD_POD_ID}-8003.proxy.runpod.net"
  MOCK_EXTRACTION="false"
fi

if [[ -z "$EXTRACTION_URL" ]]; then
  EXTRACTION_URL="http://idp-extraction:8003"
  MOCK_EXTRACTION="true"
fi

DB_PASSWORD_ENC="$(python3 -c "import urllib.parse; print(urllib.parse.quote('''${DB_PASSWORD}''', safe=''))")"

cat >"$OUT" <<EOF
# Generated by deploy/gcp/render-env-from-terraform.sh — do not commit.
COMPOSE_PROJECT_NAME=idp-prod

GCP_PROJECT_ID=${GCP_PROJECT_ID}
GCP_REGION=${GCP_REGION}
IDP_ENV=prod

ARTIFACTS_BUCKET=${ARTIFACTS_BUCKET}
REDIS_HOST=${REDIS_HOST}
CLOUD_SQL_CONNECTION=${CLOUD_SQL}
APP_VM_IP=${APP_VM_IP}
MONITORING_VM_IP=${MONITORING_VM_IP}

APP_SA_EMAIL=${APP_SA}
PREPROCESS_SA_EMAIL=${PREPROCESS_SA}
ORCHESTRATOR_SA_EMAIL=${ORCH_SA}

DB_USER=idp
DB_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql+asyncpg://idp:${DB_PASSWORD_ENC}@cloud-sql-proxy:5432/idp

REDIS_URL=redis://${REDIS_HOST}:6379/0

CALLBACK_HMAC_SECRET=${CALLBACK_SECRET}

RUNPOD_POD_ID=${RUNPOD_POD_ID}
EXTRACTION_URL=${EXTRACTION_URL}
MOCK_EXTRACTION=${MOCK_EXTRACTION}
RUNPOD_API_KEY=

GCS_BUCKET=${ARTIFACTS_BUCKET}

FIREBASE_PROJECT_ID=${GCP_PROJECT_ID}
FIREBASE_ALLOWED_BUCKETS=
ALLOWED_IMAGE_HOSTS=firebasestorage.googleapis.com,storage.googleapis.com

GOOGLE_APPLICATION_CREDENTIALS=/secrets/preprocess-sa.json
SECRETS_DIR=/opt/idp/secrets
MODELS_DIR=/opt/idp/models

DOCTAMPER_CHECKPOINT=/models/mit_unet_doctamper_best.pt
FRAUD_ENABLED=true
TAMPER_PIXEL_THRESHOLD=0.0001
MAX_IMAGE_EDGE=4096

BATCH_MAX_SIZE=48
BATCH_MAX_WAIT_MS=500
CIRCUIT_FAILURE_THRESHOLD=5
CIRCUIT_OPEN_SECONDS=30

IMAGE_REGISTRY=
IMAGE_TAG=prod

OTEL_EXPORTER_ENDPOINT=
EOF

echo "Wrote $OUT"
echo "EXTRACTION_URL=${EXTRACTION_URL} MOCK_EXTRACTION=${MOCK_EXTRACTION}"
